version: '3.7'

networks:
  dev-network:
    driver: bridge

services:

  postgres:
    container_name: 'postgres_dockerized'
    image: postgres:10
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'websocketschat_db'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - 'dev-network'

  web:
    container_name: 'websocketschat_dockerized'
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: 'Production'
      DB_CONNECTION_STRING: 'host=postgres;port=5432;database=websocketschat_db;username=postgres;password=postgres'
    depends_on:
      - 'postgres'
    networks:
      - 'dev-network'

volumes:
  pgdata: